import 'package:bl_demolition_materials/bl_demolition_materials.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_app/src/bloc/total_building_frame_bloc.dart';
import 'package:flutter_app/src/data/cell.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_layout_grid/flutter_layout_grid.dart';
import 'package:flutter_app/src/data/form_header.dart';

class OuterWallsForm extends StatelessWidget {
  const OuterWallsForm({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<TotalBuildingFrameBloc, TotalBuildingFrame>(
        builder: (context, state) {
      return Column(
        children: [
          // Exterior Wall Structures Form
          SizedBox(height: 50), // Space before next grid

          FormHeader(text: 'Ulkoseinärakenteiden osuus ja pinta-ala'),
          LayoutGrid(
            columnSizes: [
              150.px,
              100.px,
              100.px,
              100.px,
              100.px,
              100.px,
              100.px,
              100.px,
              100.px,
              100.px,
            ],
            rowSizes: List.filled(14, 50.px),
            children: [
              Cell.header(
                initialValue: 'Seinärakenne',
              ),
              Cell.column(initialValue: 'Kaksinkertainen tiiliseinä'),
              Cell.column(initialValue: 'Betonielementtiseinä'),
              Cell.column(initialValue: 'Tiiliverhoiltu seinä'),
              Cell.column(initialValue: 'Lautaseinä'),
              Cell.column(initialValue: 'Profiilipelti'),
              Cell.column(initialValue: 'Teräsprofiili sandwichrakenne'),
              Cell.column(initialValue: 'Mineriitti tai muu kivilevy'),
              Cell.column(initialValue: 'Yhteensä'),
              Cell.empty(),
              Cell.row(
                initialValue: 'Rakenteen osuus koko ulkoseinistä (%)',
              ),
              Cell.output(percentage: true, getter: () => null),
              Cell.output(percentage: true, getter: () {}),
              Cell.input(initialValue: null, percentage: true, setter: () {}),
              Cell.input(initialValue: null, percentage: true, setter: () {}),
              Cell.input(initialValue: null, percentage: true, setter: () {}),
              Cell.input(initialValue: null, percentage: true, setter: () {}),
              Cell.input(initialValue: null, percentage: true, setter: () {}),
              Cell.output(percentage: true, getter: () {}),
              Cell.empty(),
              Cell.row(initialValue: 'Pinta-ala (m2)'),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.empty(),
              Cell.header(initialValue: 'Purkumateriaalien määrä'),
              Cell.empty(),
              Cell.empty(),
              Cell.empty(),
              Cell.empty(),
              Cell.empty(),
              Cell.empty(),
              Cell.empty(),
              Cell.column(initialValue: 'Yhteensä (m3)'),
              Cell.column(initialValue: 'Yhteensä (tonnia)'),
              Cell.row(initialValue: 'Tuulensuojalevy (bituliitti, tms.)'),
              Cell.grey(),
              Cell.grey(),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.grey(),
              Cell.grey(),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.row(initialValue: 'Mineraalivilla'),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.row(initialValue: '130mm kalkki- tai punatiili'),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.row(initialValue: '20m ulkoverhouslauta'),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.row(initialValue: '11mm kipsilevy'),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.row(initialValue: 'Profiilipelti (teräs)'),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.row(initialValue: 'Puolikova kuitulevy'),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.row(initialValue: 'Styrox'),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.row(initialValue: 'Rappaus, sisä- ja ulkoseinät'),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.row(initialValue: 'Mineriittilevy'),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
              Cell.output(getter: () {}),
            ],
          ),
        ],
      );
    });
  }
}
