name: flutter_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.7
  flutter_localizations:
    sdk: flutter
  logger: ^2.5.0
  pluto_grid: ^8.0.0
  stream_mixin: ^3.0.4
  bl_demolition_materials:
    path: calculation/
  flutter_bloc: ^9.1.0
  rps: ^0.8.2
  equatable: ^2.0.7
  pdf: ^3.10.6
  printing: ^5.11.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
      - family: Carlito
        fonts:
          - asset: assets/fonts/Carlito-Regular.ttf
          - asset: assets/fonts/Carlito-Bold.ttf